### Numpy : 

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


#### Why Numpy is Needed :

* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science, where speed and resources are very important.


In [ ]:
# Installation & Importing

pip install numpy  # for installation

import numpy as np  # for importing



***1. Creating an Array :***

In [ ]:
# 1D array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print(type(arr2d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)
print(type(arr3d))



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


***2. Array Properties***

In [5]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)     # dimension
print(arr.shape)    # rows, columns
print(arr.size)     # total elements
print(arr.dtype)    # data type

2
(2, 3)
6
int64


***3. Special Array Function***


In [ ]:
# 1. np.zeros() - creates an array filled with zeros.
# Syntax : np.zeros(shape)
zeros_array = np.zeros((3, 4))  # 3 rows, 4 columns
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# 2. np.ones() - creates an array filled with ones
ones_array = np.ones((2, 5))  # 2 rows, 5 columns
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# 3. np.eye() - creates an identity matrix
identity_matrix = np.eye(4)  # 4x4 identity matrix
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# 4. np.arrange() - creates an array with a range of values
range_array = np.arange(0, 10, 2)  # start, stop, step
print(range_array)

[0 2 4 6 8]


In [ ]:
# 5. np.linspace() - creates an array of evenly spaced values between a specified range.
# Syntax : np.linspace(start, stop, num)
linspace_array = np.linspace(0, 1, 5)  # start, stop, number of values
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
# 6. np.random.rand() - creates an array of random values between 0 and 1
random_array = np.random.rand(3, 3)  # 3x3 array
print(random_array)

[[0.44049589 0.37030975 0.79872368]
 [0.71261942 0.62713134 0.85818681]
 [0.24118124 0.28049818 0.9444578 ]]


***4. Indexing & Slicing***

In [13]:
arr = np.array([10,20,30,40,50])

print(arr[0])      # first element
print(arr[-1])     # last element
print(arr[1:4])    # slicing

10
50
[20 30 40]


In [14]:
# 2D Slicing
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2[0,1])      # row 0 col 1
print(arr2[:,1])      # all rows col 1
print(arr2[0,:])      # row 0

2
[2 5]
[1 2 3]


In [15]:
# Reshaping Array
arr = np.arange(12)
reshaped = arr.reshape(3,4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


***5. Mathematical Operations***


In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [17]:
# Aggregation Function
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

21
3.5
6
1
1.707825127659933


In [18]:
np.sum(arr, axis=0)   # column-wise
np.sum(arr, axis=1)   # row-wise

array([ 6, 15])

In [19]:
# Broadcasting
arr = np.array([[1,2,3],[4,5,6]])
scalar = 10
result = arr + scalar
print(result)

[[11 12 13]
 [14 15 16]]


In [20]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


***6. Matrix Operations***

In [21]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

# Matrix multiplication
print(np.dot(a,b))
print(a @ b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# Transpose
print(a.T)  

[[1 3]
 [2 4]]


***7. Linear Algebra Module***

In [24]:
# Linear Algebra Module
import numpy as np

a = np.array([[1,2],
              [3,4]], dtype=float)

# Determinant
print("Determinant:", np.linalg.det(a))

# Inverse
print("Inverse:\n", np.linalg.inv(a))

# Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


***8. Random Module***

In [26]:
# random.seed() - sets the seed for reproducibility
np.random.seed(42)
print(np.random.rand(3,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [27]:
# np.random.randint() - generates random integers
print(np.random.randint(1, 10, (3, 3)))  # lower, upper, size       


[[8 3 6]
 [5 2 8]
 [6 2 5]]


In [28]:
# np.random.normal() - generates random numbers from a normal distribution
print(np.random.normal(0, 1, (2, 2)))  # mean, std, size

[[ 1.46237812  1.53871497]
 [-2.43910582  0.60344123]]


In [30]:
# Boolean Masking : it is used in Filtering data based on conditions, removing outliers, etc.

arr = np.array([10,20,30,40,50])

print(arr[arr > 25])

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean mask for even numbers
mask = arr % 2 == 0
print("Boolean mask for even numbers:", mask)

# Apply the boolean mask to filter even numbers
even_numbers = arr[mask]
print("Even numbers:", even_numbers)

[30 40 50]
Boolean mask for even numbers: [False  True False  True False  True False  True False  True]
Even numbers: [ 2  4  6  8 10]


***9. Stacking & Spliting***


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [32]:
# Split
arr = np.arange(10)
np.split(arr,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

***10. NumPy vs Python List :***

NumPy is faster because:

* Uses contiguous memory

* Written in C

* Supports vectorized operations

In [35]:
# Example : Python List

lst = [1, 2, 3, 4]

result = []
for i in lst:
    result.append(i * 2)

print(result)

[2, 4, 6, 8]


In [36]:
# Example : NumPy Array
import numpy as np

arr = np.array([1, 2, 3, 4])

result = arr * 2
print(result)

[2 4 6 8]


***11. Imp. Points***

1️⃣ NumPy provides a fast multi-dimensional array object called ndarray.

2️⃣ It is much faster than Python lists due to vectorization and C implementation.

3️⃣ All elements in a NumPy array must be of the same data type.

4️⃣ It supports powerful mathematical and statistical operations.

5️⃣ Broadcasting allows operations between different shaped arrays.

6️⃣ It provides built-in linear algebra functions (det, inv, eig).

7️⃣ It includes a random module for simulations and ML weight initialization.

8️⃣ It uses contiguous memory, making it memory-efficient.

9️⃣ Axis concept (axis=0, axis=1) is important for row/column operations.

🔟 It is the foundation of many ML libraries and scientific computing tools. 